/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RouteService } from "../route.service";
import { RouteCreateInput } from "./RouteCreateInput";
import { Route } from "./Route";
import { RouteFindManyArgs } from "./RouteFindManyArgs";
import { RouteWhereUniqueInput } from "./RouteWhereUniqueInput";
import { RouteUpdateInput } from "./RouteUpdateInput";
import { BusFindManyArgs } from "../../bus/base/BusFindManyArgs";
import { Bus } from "../../bus/base/Bus";
import { BusWhereUniqueInput } from "../../bus/base/BusWhereUniqueInput";
import { TicketFindManyArgs } from "../../ticket/base/TicketFindManyArgs";
import { Ticket } from "../../ticket/base/Ticket";
import { TicketWhereUniqueInput } from "../../ticket/base/TicketWhereUniqueInput";

export class RouteControllerBase {
  constructor(protected readonly service: RouteService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Route })
  async createRoute(@common.Body() data: RouteCreateInput): Promise<Route> {
    return await this.service.createRoute({
      data: {
        ...data,

        station: data.station
          ? {
              connect: data.station,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        destination: true,
        duration: true,
        id: true,
        price: true,
        routeName: true,
        source: true,

        station: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Route] })
  @ApiNestedQuery(RouteFindManyArgs)
  async routes(@common.Req() request: Request): Promise<Route[]> {
    const args = plainToClass(RouteFindManyArgs, request.query);
    return this.service.routes({
      ...args,
      select: {
        createdAt: true,
        destination: true,
        duration: true,
        id: true,
        price: true,
        routeName: true,
        source: true,

        station: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Route })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async route(
    @common.Param() params: RouteWhereUniqueInput
  ): Promise<Route | null> {
    const result = await this.service.route({
      where: params,
      select: {
        createdAt: true,
        destination: true,
        duration: true,
        id: true,
        price: true,
        routeName: true,
        source: true,

        station: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Route })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRoute(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() data: RouteUpdateInput
  ): Promise<Route | null> {
    try {
      return await this.service.updateRoute({
        where: params,
        data: {
          ...data,

          station: data.station
            ? {
                connect: data.station,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          destination: true,
          duration: true,
          id: true,
          price: true,
          routeName: true,
          source: true,

          station: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Route })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRoute(
    @common.Param() params: RouteWhereUniqueInput
  ): Promise<Route | null> {
    try {
      return await this.service.deleteRoute({
        where: params,
        select: {
          createdAt: true,
          destination: true,
          duration: true,
          id: true,
          price: true,
          routeName: true,
          source: true,

          station: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/buses")
  @ApiNestedQuery(BusFindManyArgs)
  async findBuses(
    @common.Req() request: Request,
    @common.Param() params: RouteWhereUniqueInput
  ): Promise<Bus[]> {
    const query = plainToClass(BusFindManyArgs, request.query);
    const results = await this.service.findBuses(params.id, {
      ...query,
      select: {
        busNumber: true,
        capacity: true,
        createdAt: true,
        driverName: true,
        id: true,
        licenseNumber: true,

        route: {
          select: {
            id: true,
          },
        },

        station: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/buses")
  async connectBuses(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: BusWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      buses: {
        connect: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/buses")
  async updateBuses(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: BusWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      buses: {
        set: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/buses")
  async disconnectBuses(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: BusWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      buses: {
        disconnect: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/tickets")
  @ApiNestedQuery(TicketFindManyArgs)
  async findTickets(
    @common.Req() request: Request,
    @common.Param() params: RouteWhereUniqueInput
  ): Promise<Ticket[]> {
    const query = plainToClass(TicketFindManyArgs, request.query);
    const results = await this.service.findTickets(params.id, {
      ...query,
      select: {
        createdAt: true,
        fullName: true,
        id: true,
        journeyDate: true,
        phoneNumber: true,
        price: true,

        route: {
          select: {
            id: true,
          },
        },

        seatNumber: true,

        station: {
          select: {
            id: true,
          },
        },

        ticketNumber: true,
        updatedAt: true,
        vehicle: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tickets")
  async connectTickets(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        connect: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tickets")
  async updateTickets(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        set: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tickets")
  async disconnectTickets(
    @common.Param() params: RouteWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        disconnect: body,
      },
    };
    await this.service.updateRoute({
      where: params,
      data,
      select: { id: true },
    });
  }
}
